#!/bin/sh
#
# Copyright (c) 2021, Lev Kujawski.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software")
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

if test $# -ne 2; then
    echo "$0: Insufficient arguments" >&2
    exit 1
fi

if test -n "${TMPDIR}"; then
    TMPDIR=`echo "${TMPDIR}" | sed -e 's,/$,,'`
else
    TMPDIR="/tmp"; export TMPDIR
fi

unset GNATKRUNCH
if test -n "${ADAKRUNCH}"; then
    GNATKRUNCH="-gnatk${ADAKRUNCH}"
fi

if test -z "${USER}" -a -z "${LOGNAME}"; then
    USER="unknown"
fi

GNATSCAN_TMPDIR="${TMPDIR}/gnatscan.${USER:-$LOGNAME}.$$"

if mkdir "${GNATSCAN_TMPDIR}"; then
    trap 'rm -f -r ${GNATSCAN_TMPDIR}' EXIT
    ADA_SOURCE=`basename "${1}"`
    ADA_OBJECT=`echo "${ADA_SOURCE}" | sed -e 's,.ad[bs]$,.o,'`
    ADA_OBJECT="${GNATSCAN_TMPDIR}/${ADA_OBJECT}"
    gcc -gnatQ ${GNATKRUNCH} ${2} -c "${1}" -o "${ADA_OBJECT}" 2>/dev/null
    printf ".IMPLICIT: "
    gnatls -d -s "${ADA_OBJECT}" | sed -e "s,${ADA_SOURCE},," | xargs | tr -d '\n'
    echo
else
    exit 1
fi
