name: AST CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  ubuntu:

    runs-on: ubuntu-20.04

    env:
      REGRESSFLAGS: -v
      TZ: UTC
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install libdb5.3-dev

    - name: Build
      run: bin/package make

    - name: Test
      run: bin/package test nmake

    - name: Report
      run: bin/package results test | tail -n +2 | tee test.log

    - name: Validate
      run: cmp test.log .github/conform.log
