name: AST CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install libdb5.3-dev

    - name: Build
      run: ./bin/package flat make

    - name: Test
      run: ./bin/package flat test nmake

    - name: Report
      run: ./bin/package flat results test 2>&1 | tail -n +2 | tee test.log

    - name: Validate
      run: cmp test.log .github/conform.log
